add status code 201 to post new card and create test to post
kacper-echaust/fischkapp-api pull request #14
Opened 2024-10-10 14:32 UTC by kacper-echaust

2024-10-10 14:33 UTC, NerdbordMentor requested changes
## Overall Feedback 7/10

The code changes address the task requirements to a significant extent. The implementation includes tests for creating new flashcards and checks for the correct status code and fields. However, there is a missing test case for handling the scenario where a card with a specific front value already exists, which is crucial for meeting all the task requirements.

### Things Missing:

- [x] Test case for ensuring the function returns a status code of 400 when a card with a specific front value already exists.

### Things That Went Well:

- The function now correctly returns a status code of 201 when a new card is created.
- The test for creating a new flashcard with the correct fields is well-implemented and checks for the necessary attributes.

2024-10-10 19:29 UTC, Sumick requested changes
You mixed 2 different test cases in one. You should have 3 tests as specified in task description

2024-10-10 19:29 UTC, Sumick commented on src/tests/index.test.ts
> +				expect(res2.status).toBe(400)
**issue:** These are 2 different scenarios. you should not place them in one test. I mean you check if `function returns status code 201` or it `returns a status code of 400 when card with specific front value already exists`.

2024-10-11 14:09 UTC, NerdbordMentor requested changes
## Overall Feedback 7/10

The solution meets most of the task requirements, including testing for the correct status codes and ensuring that a new flashcard is created with the correct fields. However, there are some issues that need to be addressed to fully meet the requirements and ensure robust functionality.

### Things Missing:

- [x] The test for creating a new flashcard does not verify that the flashcard is created with the correct fields. The test should include assertions to check that the returned flashcard contains the expected 'front', 'back', 'author', and 'tags' fields.

### Things That Went Well:

- The implementation correctly returns a status code of 201 when a new flashcard is created.
- The code properly handles the case where a card with a specific front value already exists, returning a status code of 400.

2024-10-11 14:12 UTC, NerdbordMentor requested changes
## Overall Feedback 7/10

The solution meets most of the task requirements, with tests implemented for the creation of new flashcards and handling of duplicate entries. The code changes include the necessary logic to return the correct status codes and create flashcards with the specified fields. However, there are some issues in the test implementation that need to be addressed to ensure full compliance with the requirements.

### Things Missing:

- [x] The test for creating a new flashcard does not verify that the flashcard is created with the correct fields.

### Things That Went Well:

- The use of async/await in the route handler is well-implemented, ensuring asynchronous operations are handled correctly.
- The test for checking the status code 400 when a duplicate card is created is correctly implemented.

2024-10-11 14:13 UTC, NerdbordMentor requested changes
## Overall Feedback 7/10

The solution meets most of the task requirements, with tests implemented for the creation of new flashcards and handling of duplicate entries. The code changes include the necessary logic to return the correct status codes (201 and 400) and create flashcards with the specified fields. However, there are some issues in the test implementation that need to be addressed to ensure the tests are correctly validating the functionality.

### Things Missing:

- [ ] The test for creating a new flashcard does not verify that the flashcard is created with the correct fields.
- [ ] The test for handling duplicate entries does not send the correct payload to trigger the duplicate check.

### Things That Went Well:

- The use of async/await in the route handler is well-implemented, providing clean and readable asynchronous code.
- The status codes for successful creation and duplicate entry are correctly handled in the business logic.

2024-10-13 20:25 UTC, Sumick requested changes
Yea, Nerdy is right - you have 2 issues to resolve here, as these tests have errors

2024-10-13 20:25 UTC, Sumick commented on src/tests/index.test.ts
> +					.send(initialCardsMock[0].front)
**issue:** Nerdy is right, you should pass whole object instead of string. currently it wont work

2024-10-13 20:25 UTC, Sumick commented on src/tests/index.test.ts
> +				expect({ front: 'front', back: 'back', author: 'author', tags: ['tag1', 'tag2'] })
**issue:** Nerdy is right, you should check values of created object. this second `expect` is written wrong - it does not check anything

2024-10-16 06:05 UTC, NerdbordMentor approved these changes
## Overall Feedback 8/10

The code changes have addressed the majority of the task requirements effectively. The implementation now includes separate test cases for creating new flashcards and handling duplicate entries, which aligns with the task description. The tests correctly verify the status codes and ensure that flashcards are created with the correct fields. However, there is a minor issue with the error handling in the route handler that could be improved for robustness.

### Things Missing:

- [] Error handling in the route handler could be improved to provide more informative responses in case of unexpected errors.

### Things That Went Well:

- The separation of test cases for different scenarios is well-implemented, ensuring clarity and focus in each test.
- The use of `expect` to verify the status codes and the structure of the created flashcard is correctly implemented, ensuring that the tests are meaningful and accurate.

2024-10-16 06:07 UTC, merged